api_user_register:
  path: /api/user/register/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_register}
  methods: POST
api_user_edit:
  path: /api/user/edit/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_edit}
  methods: POST
api_user_token:
  path: /api/user/token/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_token}
  methods: POST
api_user_login:
  path: /api/user/login/{username}/{password}/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_login}
  methods: GET
user_user_index:
  path: /users/index.html
  defaults: { _controller: UserBundle:User:index}
user_user_edit:
  path: /users/edit/{id}.html
  defaults: { _controller: UserBundle:User:edit}
  requirements:
      id:  \d+
user_user_comments:
  path: /users/comments/{id}.html
  defaults: { _controller: UserBundle:User:comments}
  requirements:
      id:  \d+
user_user_ratings:
  path: /users/ratings/{id}.html
  defaults: { _controller: UserBundle:User:ratings}
  requirements:
      id:  \d+
user_user_delete:
  path: /users/delete/{id}.html
  defaults: { _controller: UserBundle:User:delete}
  requirements:
      id:  \d+
api_user_check:
  path: /api/user/check/{id}/{key}/{token}/{purchase}/
  defaults: { _controller: UserBundle:User:api_check}
  methods: GET